export interface HelpSection {
  id: number;
  title: string;
  content: string[];
}

export const helpIndex: string[] = [
  'FIELD_NODES HELP INDEX',
  '',
  '[1] Basic Commands',
  '[2] Working with Nodes',
  '[3] Field Codes and IDs',
  '[4] Linking and Relations',
  '[5] Reflections and Versions',
  '[6] Tagging and Search',
  '[7] Managing Your Archive',
  '[8] Collaboration and Stewardship',
  '[9] Troubleshooting',
  '[10] Common Questions',
  '',
  'Type a number (1–10) or click a section to begin.',
  '',
];

export const helpSections: HelpSection[] = [
  {
    id: 1,
    title: 'Basic Commands',
    content: [
      '',
      'BASIC COMMANDS',
      '',
      '/explore              → browse fields and nodes',
      '/import [are.na-link] → create a new Raw Node',
      '/node                 → create a Raw Node manually',
      '/reflect [id]         → add a Reflection to a Node',
      '/link [A] [B]         → connect two Nodes',
      '/map                  → view your relational graph',
      '/help                 → open help index',
      '/orientate            → restart system tutorial',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 2,
    title: 'Working with Nodes',
    content: [
      '',
      'WORKING WITH NODES',
      '',
      'Node types: Raw, Support, Reflection, Context, Connection, Steward',
      '',
      'create a node      /node',
      'edit a node        open node → press [e]',
      'archive a node     /archive [id]',
      'view history       /history [id]',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 3,
    title: 'Field Codes and IDs',
    content: [
      '',
      'FIELD CODES AND IDS',
      '',
      'FT — feminist_theory',
      'SD — system_design',
      'MA — mutual_aid',
      'AR — archiving',
      'AI — algorithmic_infrastructures',
      '',
      'Raw Node:        FN-FT-001',
      'Support Node:    FN-FT-001.S01',
      'Reflection Node: FN-FT-001.R01',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 4,
    title: 'Linking and Relations',
    content: [
      '',
      'LINKING AND RELATIONS',
      '',
      '/link [A] [B]         → create connection',
      '/link [A] [B] support → specify relation type',
      '/unlink [A] [B]       → remove a connection',
      '',
      'Supported relations:',
      'supports, contrasts, parallels, derived_from, verifies',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 5,
    title: 'Reflections and Versions',
    content: [
      '',
      'REFLECTIONS AND VERSIONS',
      '',
      '/reflect [id]         → add a new reflection',
      '/view [id] --timeline → show all reflections chronologically',
      '',
      'Reflections can include short notes, media, or Are.na embeds.',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 6,
    title: 'Tagging and Search',
    content: [
      '',
      'TAGGING AND SEARCH',
      '',
      '/find tag:[keyword]',
      '/find field:[FT]',
      '/find author:[handle]',
      '/find "algorithmic bias"',
      '',
      'Tag rules:',
      '• use lowercase',
      '• avoid redundancy',
      '• prefer conceptual tags (e.g. "care", "maintenance")',
      '• Are.na tags import automatically',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 7,
    title: 'Managing Your Archive',
    content: [
      '',
      'MANAGING YOUR ARCHIVE',
      '',
      '/backup            → export JSON or Markdown',
      '/import-local      → load saved archive',
      '/archive [id]      → move node to inactive state',
      '/unarchive [id]    → restore node',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 8,
    title: 'Collaboration and Stewardship',
    content: [
      '',
      'COLLABORATION AND STEWARDSHIP',
      '',
      'Stewards can:',
      '• verify sources',
      '• tag and reclassify',
      '• merge duplicates',
      '• manage archive versions',
      '',
      'Commands:',
      '/verify [id]       → add a Steward Note',
      '/merge [A] [B]     → combine nodes',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 9,
    title: 'Troubleshooting',
    content: [
      '',
      'TROUBLESHOOTING',
      '',
      'connection error  → check API key or Are.na status',
      'duplicate import  → node already exists (search by origin)',
      'command not found → use /help to list available syntax',
      'graph not rendering → reload or clear cache',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
  {
    id: 10,
    title: 'Common Questions',
    content: [
      '',
      'COMMON QUESTIONS',
      '',
      '“Can anyone edit my nodes?”',
      'Only you and designated stewards.',
      '',
      '“Why do I need fields?”',
      'They organize thought, not control it — like folders with relationships.',
      '',
      '“Can I use this without Are.na?”',
      'Yes — /node lets you start from scratch, but Are.na makes it easier.',
      '',
      '“Is this social?”',
      'Not in the traditional sense — it’s relational, not performative.',
      '',
      'curious why this system exists? type /orientate to revisit the manifesto.',
      '',
      'return to help index? (y/n)',
      '',
    ],
  },
];
