// Field Nodes Orientation Questions
// FN0.00 — orientation protocol

export interface OrientationQuestion {
  id: number;
  title: string;
  content: string[];
}

export const orientationQuestions: OrientationQuestion[] = [
  {
    id: 1,
    title: 'What is Field Nodes?',
    content: [
      '',
      'What is Field Nodes?',
      '',
      'Field Nodes is a collaborative research protocol — not a social platform.',
      '',
      'It is a system where ideas live as nodes: connected, editable, and part',
      'of a collective field of knowledge. Unlike feeds or timelines, Field Nodes',
      'organizes knowledge through relation, not reaction.',
      '',
      'At its core, Field Nodes is about:',
      '',
      '• relational knowledge — ideas exist in connection to other ideas',
      '• care-driven infrastructure — built for slow, intentional participation',
      '• collective thinking — not individual broadcast, but collaborative building',
      '',
      'It\'s not social media. It\'s not a feed. It\'s a field.',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 2,
    title: 'Why does it exist?',
    content: [
      '',
      'Why does Field Nodes exist?',
      '',
      'We are rethinking systems built on attention, speed, and extraction.',
      '',
      'Most digital platforms are designed around:',
      '• maximizing engagement',
      '• algorithmic amplification',
      '• data extraction',
      '• reaction over reflection',
      '',
      'Field Nodes exists to explore a different paradigm.',
      '',
      'Inspired by feminist systems theory, it centers:',
      '• care and maintenance over growth metrics',
      '• reflection over reaction',
      '• relation over ranking',
      '• ethics and affect as infrastructure',
      '',
      'The question Field Nodes asks:',
      'What would technology look like if we designed it with care?',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 3,
    title: 'How does Field Nodes work?',
    content: [
      '',
      'How does Field Nodes work?',
      '',
      'Field Nodes operates through a simple architecture:',
      '',
      'FIELDS → thematic clusters that organize nodes',
      'NODES → modular knowledge units (ideas, reflections, connections)',
      'RELATIONS → links between nodes that build webs of meaning',
      'METADATA → tags, types, and origin information',
      '',
      'Information moves through connection and reflection, not ranking.',
      '',
      'Visualized, knowledge looks like an ecology:',
      'nodes cluster in fields, fields overlap, relations weave between them.',
      '',
      'Unlike algorithmic feeds, Field Nodes surfaces knowledge through:',
      '• exploration (browsing fields and nodes)',
      '• creation (adding your own nodes)',
      '• reflection (responding to existing ideas)',
      '• connection (linking related concepts)',
      '',
      'The architecture is open, human-readable, and machine-parsable.',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 4,
    title: 'What is a Node?',
    content: [
      '',
      'What is a Node?',
      '',
      'A node is a modular knowledge unit — the basic building block of Field Nodes.',
      '',
      'Each node contains:',
      '',
      '• TITLE — a clear, descriptive name',
      '• BODY — the content (text, markdown, links)',
      '• TAGS — thematic labels for discovery',
      '• RELATIONS — connections to other nodes',
      '• METADATA — type, origin, timestamp, creator',
      '• ORIGIN — source (often from Are.na)',
      '',
      'Nodes follow an ID structure:',
      'FN-{FIELD}-{NNN}',
      '',
      'Example:',
      'FN-0-001 (a node in the general/orientation field)',
      'FN-FT-045 (a node in the feminist_theory field)',
      '',
      'What makes nodes powerful:',
      'your thoughts become artifacts. Each idea is a persistent,',
      'linkable, referenceable unit in the collective field.',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 5,
    title: 'How are Nodes structured?',
    content: [
      '',
      'How are Nodes structured?',
      '',
      'Nodes come in different types, each serving a distinct purpose:',
      '',
      'RAW → original ideas, imported content, base knowledge',
      'SUPPORT → additions that extend or clarify existing nodes',
      'REFLECTION → thoughtful responses and commentary',
      'CONTEXT → background information, framing, history',
      'CONNECTION → explicit links between nodes (A → B)',
      'STEWARD → maintenance, curation, field-keeping',
      '',
      'Nodes form hierarchies:',
      'a Support node extends a Raw node.',
      'a Reflection responds to any node.',
      'Connections weave webs between them.',
      '',
      'This structure is both human-readable and machine-parsable.',
      'It\'s a design pattern for thought — a way to make knowledge',
      'modular, composable, and traceable.',
      '',
      'The type system allows Field Nodes to understand:',
      '• what kind of knowledge each node represents',
      '• how nodes relate to each other',
      '• the flow of ideas through the field',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 6,
    title: 'What is a Field?',
    content: [
      '',
      'What is a Field?',
      '',
      'A field is a thematic cluster — an ecology of nodes.',
      '',
      'Fields organize related ideas:',
      '• feminist_theory (FT)',
      '• system_design (SD)',
      '• mutual_aid (MA)',
      '• archiving (AR)',
      '• etc.',
      '',
      'Field codes are short identifiers:',
      'FT = feminist_theory',
      'SD = system_design',
      '',
      'Fields evolve through collaboration, not moderation.',
      'When multiple participants contribute to a field, it grows.',
      'Fields overlap and intersect like real intellectual landscapes.',
      '',
      'What makes fields alive:',
      'they feel like living ecosystems rather than static categories.',
      'Nodes cluster naturally, connections form organically,',
      'and the field becomes a map of collective understanding.',
      '',
      'A node can belong to multiple fields through tags.',
      'A field is defined by the nodes it contains.',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 7,
    title: 'How do I create and connect Nodes?',
    content: [
      '',
      'How do I create and connect Nodes?',
      '',
      'Creating and connecting nodes is straightforward:',
      '',
      'BROWSE:',
      '  /explore → browse existing fields and nodes',
      '',
      'CREATE:',
      '  /import [are.na-link] → create a node from Are.na',
      '  /node → create a new raw node',
      '',
      'CONNECT:',
      '  /reflect [node_id] → add a reflection to a node',
      '  /link [node_A] [node_B] → create a connection',
      '',
      'Example flow:',
      '',
      '  1. /explore',
      '     → browse feminist_theory field',
      '',
      '  2. /node',
      '     → create "The cyborg as infrastructure"',
      '',
      '  3. /reflect FN-0-045',
      '     → reflect on an existing node',
      '',
      '  4. /link FN-FT-001 FN-FT-045',
      '     → connect two related nodes',
      '',
      'What happens:',
      'each action builds your web of knowledge.',
      'You\'re not consuming someone else\'s feed —',
      'you\'re constructing your own understanding,',
      'linked to the collective field.',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 8,
    title: 'What are best practices for contribution?',
    content: [
      '',
      'What are best practices for contribution?',
      '',
      'Field Nodes is built on a culture of care. Good citizenship means:',
      '',
      'MOVE SLOWLY',
      '  context matters. Read before adding. Understand connections.',
      '',
      'CITE AND CREDIT',
      '  when you build on others\' ideas, acknowledge them.',
      '  trace the lineage of thought.',
      '',
      'DON\'T DUPLICATE',
      '  search first. Link to existing nodes rather than recreating.',
      '',
      'REFLECT, DON\'T REACT',
      '  thoughtful responses deepen the field.',
      '  quick reactions create noise.',
      '',
      'NAME CLEARLY',
      '  use descriptive titles so others can find your nodes.',
      '  tag thoughtfully for discovery.',
      '',
      'CARE FOR THE FIELD',
      '  good Field Nodes citizenship means maintaining and',
      '  stewarding the collective knowledge.',
      '',
      'This is not just about technology —',
      'it\'s about building culture differently.',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 9,
    title: 'How does Field Nodes relate to Are.na and the wider web?',
    content: [
      '',
      'How does Field Nodes relate to Are.na and the wider web?',
      '',
      'Field Nodes is interoperable — not walled off, but connected.',
      '',
      'ARE.NA INTEGRATION',
      '',
      'Import process:',
      '  /import [are.na-link]',
      '  → pulls metadata, tags, and content',
      '  → preserves origin information',
      '  → creates node with Are.na attribution',
      '',
      'Reflections can push back to Are.na,',
      'creating a bidirectional flow of knowledge.',
      '',
      'THE SLOW WEB',
      '',
      'Field Nodes sits within the "slow web" movement:',
      '• Small Web',
      '• IndieWeb',
      '• community-controlled infrastructure',
      '• protocols over platforms',
      '',
      'It shares values with:',
      '• Are.na (curation without algorithms)',
      '• Neocities (independent hosting)',
      '• Scuttlebutt (peer-to-peer social)',
      '',
      'But Field Nodes adds:',
      '• explicit structure (nodes, fields, types)',
      '• relational knowledge mapping',
      '• feminist systems thinking',
      '',
      'It\'s connected to thoughtful internet spaces,',
      'not isolated in a walled garden.',
      '',
      'return to orientation index? (y/n)',
      '',
    ],
  },
  {
    id: 10,
    title: 'How can I think with Field Nodes — not just use it?',
    content: [
      '',
      'How can I think with Field Nodes — not just use it?',
      '',
      'This is the heart of Field Nodes.',
      '',
      'It\'s not just software — it\'s a system of care.',
      '',
      'Thinking with Field Nodes means:',
      '',
      'REFLECTING ON RELATION',
      '  What does it mean to design systems that care?',
      '  How do we build infrastructure that supports',
      '  maintenance over growth, relation over extraction?',
      '',
      'LEARNING AS MAINTENANCE',
      '  Knowledge is not just consumption.',
      '  It\'s active participation, stewardship,',
      '  and collective building.',
      '',
      'KNOWLEDGE AS RELATION',
      '  Ideas don\'t exist in isolation.',
      '  They exist in connection, context, and care.',
      '',
      'Field Nodes is an experiment:',
      'what if we designed technology that felt',
      'more like tending a garden than managing a feed?',
      '',
      'You are now part of the field.',
      'Ideas move through relation, not reaction.',
      '',
      'press Enter to continue',
      '',
    ],
  },
];

export const orientationIndex: string[] = [
  'FIELD_NODES ORIENTATION',
  '',
  '[1] What is Field Nodes?',
  '[2] Why does it exist?',
  '[3] How does Field Nodes work?',
  '[4] What is a Node?',
  '[5] How are Nodes structured?',
  '[6] What is a Field?',
  '[7] How do I create and connect Nodes?',
  '[8] What are best practices for contribution?',
  '[9] How does Field Nodes relate to Are.na and the wider web?',
  '[10] How can I think with Field Nodes — not just use it?',
  '',
  'Type a number (1–10) or click a question to begin.',
  '',
];

